/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function AlexLen(props) {

  const [letras] = useBox(() => ({
    mass: 1,
    args: [2, .25, .5],
    material: {
        friction: 1,
        restitution: 0
    },
    ...props
  }));

  const { nodes, materials } = useGLTF("/Models/AlexLen.glb");
  return (
    <group ref={letras} {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={[0.7, 0.5, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_3.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_4.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_5.geometry}
          material={materials.Letras}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/AlexLen.glb");