/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function AlexLetras(props) {

  const [letras] = useBox(() => ({
    mass: 1,
    args: [3, .25, 1],
    material: {
        friction: 1,
        restitution: 0
    },
    ...props
  }));

  const { nodes, materials } = useGLTF("/Models/AlexLetras.glb");
  return (
    <group ref={letras} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[0.73, 0.29, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Models/AlexLetras.glb");