/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function AlexFrame(props) {

    const [letras] = useBox(() => ({
        mass: 1,
        args: [2, .25, .5],
        material: {
            friction: 1,
            restitution: 0
        },
        ...props
      }));

  const { nodes, materials } = useGLTF("/Models/AlexFrame.glb");
  return (
    <group ref={letras} {...props} dispose={null}>
      <group position={[-1.72, 0, -0.01]} scale={[0.5, 0.7, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_4.geometry}
          material={materials.Letras}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_5.geometry}
          material={materials["Material.009"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/AlexFrame.glb");