/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function BarrasLen(props) {

    const [letras] = useBox(() => ({
        mass: 1,
        args: [1, 1, 1],
        material: {
            friction: 1,
            restitution: 0
        },
        ...props
    }));

  const { nodes, materials } = useGLTF("/Models/barrasLen.glb");

  return (
    <group ref={letras} {...props} dispose={null} >
      <group  position={[0,.5,2]} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_4.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.006"]}
        position={[3.86, -4, 13.79-6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.Letras}
        position={[6.07, 0.89, 9.66-6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials.Letras}
        position={[6.01, 1.29, -2.01-6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials.Letras}
        position={[3.85, -4, 5.9-6]}
      />
    </group>
  );
}

useGLTF.preload("/Models/barrasLen.glb");