/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Html } from "@react-three/drei";

export function CartelesMariana(props) {
  const { nodes, materials } = useGLTF("/Models/cartelesCarlos.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        position={[25, 35.68, 0]}
        rotation={[0, -0.79, 0]}
        scale={[1, 0.5, 1]}
        >
        <Html scale={7} transform position={[0, 0, 0.05]} >
          <div className="annotation-Mariana">
              Art Gallery Website
          </div>
        </Html>
        </mesh>
      <mesh
        castShadow
        receiveShadow
        position={[-25, 35.68, 0]}
        rotation={[0, 0.8, 0]}
        scale={[1, 0.5, 1]}
      >
          <Html scale={7} transform position={[0, 0, 0.05]} >
            <div className="annotation-Mariana">
            Tic Tac Toe
            </div>
        </Html>
      </mesh>
    <mesh
        castShadow
        receiveShadow
        position={[-40, 35.68, 30]}
        rotation={[0, 1.56, 0]}
        scale={[1, 0.5, 1]}
        >
        <Html scale={7} transform position={[0, 0, 0.05]} >
          <div className="annotation-Mariana">
            To Do List
          </div>
        </Html>
    </mesh>
    <mesh
        castShadow
        receiveShadow
        position={[40, 35.68, 30]}
        rotation={[0, -1.57, 0]}
        scale={[1, 0.5, 1]}
        >
        <Html scale={7} transform position={[0, 0, 0.05]} >
          <div className="annotation-Mariana">
            My first videogame
          </div>
        </Html>
    </mesh>
    </group>
  );
}

useGLTF.preload("/Models/cartelesCarlos.glb");
