/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
generamos el frame para el diseño
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function MarFrame(props) {
    
    const [letras] = useBox(() => ({
        mass: 1,
        args: [2, .25, .5],
        material: {
            friction: 1,
            restitution: 0
        },
        ...props
      }));

  const { nodes, materials } = useGLTF("/Models/MarFrame.glb");
  return (
    <group ref={letras} {...props} dispose={null}>
      <group position={[0.42, 0.06, -0.22]} scale={[0.5, 0.5, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_3.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_4.geometry}
          material={materials.Letras}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/MarFrame.glb");
