/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Html } from "@react-three/drei";
import { Carlos } from "./Carlos";

//fotos Carlos
import img1 from "./Img/calculadora.jpg";
import img2 from "./Img/EditMe.jpg";
import img3 from "./Img/cripto.png";
import img4 from "./Img/Gato.png";


export function Pizarras(props) {
  const { nodes, materials } = useGLTF("/Models/pizarras.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[2.81, 2.21, -17.88]} scale={8.52}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials.Madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials.Hojas}
        />
      </group>
      <group position={[25, 2, 0]} rotation={[0, -Math.PI / 4, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.Screen}
          
        >
          <Html occlude transform position={[0, 10.85, 0.05]} >
            <Carlos img={img1}/>
          </Html>
        </mesh>
      </group>
      <group position={[40.09, 2, 30]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials.Madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.Screen}
        >
          <Html occlude transform position={[0, 10.85, 0.05]} >
            <Carlos img={img2}/>
          </Html>
        </mesh>
      </group>
      <group position={[-40, 2, 30]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Screen}
          >
          <Html occlude transform position={[0, 10.85, 0.05]} >
            <Carlos img={img3}/>
          </Html>
          </mesh>
      </group>
      <group position={[-25, 2, 0]} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials.Madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Screen}
          >
          <Html occlude transform position={[0, 10.85, 0.05]} >
            <Carlos img={img4}/>
          </Html>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/pizarras.glb");