/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function TeclasC(props) {
    const [cubeRef, api] = useBox(() => ({
      mass: 1,
      args: [0.5, .4, 0.5],
      material: {
      friction: .5,
      restitution: 0
      },
      ...props
    }));

  const { nodes, materials } = useGLTF("/Models/TeclasC.glb");

  return (
      <group  ref={cubeRef}  {...props} dispose={null}>
        <group position={[0.02, 0, -0.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text005.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text005_1.geometry}
            material={materials["Material.003"]}
          />
        </group>
      </group>
    );
  
}

useGLTF.preload("/Models/TeclasC.glb");
